[package]
name = "lexer"
version = "0.0.1"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
logos = "0.14.0"
tokens = { workspace = true }
token_maps = { workspace = true }
macros = { workspace = true }
unicode_categories = "0.1.1"

[dev-dependencies]
rstest = "0.19.0"
pretty_assertions.workspace = true
