[package]
name = "tokenizer"
version = "0.0.1"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
logos = "0.14.0"
tokens = { workspace = true }
token_maps = { workspace = true }
macros = { workspace = true }

[dev-dependencies]
rstest = "0.18.2"
